---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bot-hello-secret
  namespace: infra
spec:
  encryptedData:
    BOT_TOKEN: AgDFJKjiLWQWUV/n40Cd73JBAVEWTjQU5Bc6PyJhIfiX410P1SOoAzqJQqTB/nMfpkfCV1aw9jy96+ymZyPU/b5PVBOx/VskErpLlc2jH3VECUtMZk4i2lzCHps468x/lsuYlB969FRgH8NdJn9t7DFvNqIcJIH0v1QQ/feZMbcaPhJChntJf6nVkGo32sdlfAvswQg2sDIvB/fXm8QZHiTq7IuK7pRbj/V9iLxrQJo9x4vt3wPBUxk2hYct2AZISiVMo/U1+a8TICcRlD2ashrc7WehDd/+WIK6OMyQ7RjvPf1tTC2GJb8Jp3pP/3Ivr447FozYoVmpyKoJ6lpDfTII/SetcFFI5EZZaZWtiknfnDsad/WaSxBTZ0NG4vUnCIwcXPeGV61MkgjUxjGkWBvf7yAGbwrfFvBLmxJLSAkG8fun31r4z8AZRL6BVwu/MH56lvE42tnQRtJRF/BxSyW5xcY5AOAX4wOju3vUg8Jc4FqPBMx8GF/6ayBNa7xwx+JgKGs0AfuGtVpE2kX3m/wLaBK2ddaJP94FZu55VC/oRR5JidzxxCuMwKdlsP0hS9nSEPzy5E7SXV9Pk+KwPKK2Y6Hw/ISvT5w/7JoTyhyf8Yw6A6IqcHicmZ37ZnJcZNPfYwBu52OxuC8UXjLqkhqZHiUV6HuJERVd7w9BxgrYpAQ6uMZIAD3DxZRm8WHImdcJNN00UVevp5U9SamT/HO6Q5xec+EBbpbeiJ6SbnYhqBPHffN2F8hQSJ2YkPk1
  template:
    metadata:
      creationTimestamp: null
      name: bot-hello-secret
      namespace: infra
