apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bot-hello
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gabela626-coder/boti-gitops
    targetRevision: main
    path: apps/bot-hello
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
